In [1]:
import pandas as pd
import numpy as np

In [2]:
result = pd.read_csv('https://media.githubusercontent.com/media/StackExchange/Survey/refs/heads/main/packages/archive/2025/results.csv')
result.head()

/tmp/ipykernel_586148/2305554364.py:1: DtypeWarning: Columns (56,74,92,97,98,105,109,110,132,162,165) have mixed types. Specify dtype option on import or set low_memory=False.
  result = pd.read_csv('https://media.githubusercontent.com/media/StackExchange/Survey/refs/heads/main/packages/archive/2025/results.csv')

,ResponseId,MainBranch,Age,EdLevel,Employment,EmploymentAddl,WorkExp,LearnCodeChoose,LearnCode,LearnCodeAI,...,AIAgentOrchestration,AIAgentOrchWrite,AIAgentObserveSecure,AIAgentObsWrite,AIAgentExternal,AIAgentExtWrite,AIHuman,AIOpen,ConvertedCompYearly,JobSat
0,1,I am a developer by profession,25-34 years old,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",Employed,"Caring for dependents (children, elderly, etc.)",8.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools for...",...,Vertex AI,NaN,NaN,NaN,ChatGPT,NaN,When I don’t trust AI’s answers,"Troubleshooting, profiling, debugging",61256.0,10.0
1,2,I am a developer by profession,25-34 years old,"Associate degree (A.A., A.S., etc.)",Employed,NaN,2.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools for...",...,NaN,NaN,NaN,NaN,NaN,NaN,When I don’t trust AI’s answers;When I want to...,All skills. AI is a flop.,104413.0,9.0
2,3,I am a developer by profession,35-44 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)","Independent contractor, freelancer, or self-em...",None of the above,10.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools for...",...,NaN,NaN,NaN,NaN,ChatGPT;Claude Code;GitHub Copilot;Google Gemini,NaN,When I don’t trust AI’s answers;When I want to...,"Understand how things actually work, problem s...",53061.0,8.0
3,4,I am a developer by profession,35-44 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Employed,None of the above,4.0,"Yes, I am not new to coding but am learning ne...","Other online resources (e.g. standard search, ...","Yes, I learned how to use AI-enabled tools for...",...,NaN,NaN,NaN,NaN,ChatGPT;Claude Code,NaN,When I don’t trust AI’s answers;When I want to...,NaN,36197.0,6.0
4,5,I am a developer by profession,35-44 years old,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)","Independent contractor, freelancer, or self-em...","Caring for dependents (children, elderly, etc.)",21.0,"No, I am not new to coding and did not learn n...",NaN,"Yes, I learned how to use AI-enabled tools for...",...,NaN,NaN,NaN,NaN,NaN,NaN,When I don’t trust AI’s answers,"critical thinking, the skill to define the tas...",60000.0,7.0

In [3]:
result = pd.read_csv('https://media.githubusercontent.com/media/StackExchange/Survey/refs/heads/main/packages/archive/2025/results.csv')
result.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 49191 entries, 0 to 49190
Columns: 172 entries, ResponseId to JobSat
dtypes: float64(52), int64(1), object(119)
memory usage: 64.6+ MB

/tmp/ipykernel_586148/148043814.py:1: DtypeWarning: Columns (56,74,92,97,98,105,109,110,132,162,165) have mixed types. Specify dtype option on import or set low_memory=False.
  result = pd.read_csv('https://media.githubusercontent.com/media/StackExchange/Survey/refs/heads/main/packages/archive/2025/results.csv')

In [4]:
schema = pd.read_csv('https://media.githubusercontent.com/media/StackExchange/Survey/refs/heads/main/packages/archive/2025/schema.csv')
schema.head()

,qid,qname,question,type,sub,sq_id
0,QID18,TechEndorse_1,What attracts you to a technology or causes yo...,RO,AI integration or AI Agent capabilities,1.0
1,QID18,TechEndorse_2,What attracts you to a technology or causes yo...,RO,Easy-to-use API,2.0
2,QID18,TechEndorse_3,What attracts you to a technology or causes yo...,RO,Robust and complete API,3.0
3,QID18,TechEndorse_4,What attracts you to a technology or causes yo...,RO,Customizable and manageable codebase,4.0
4,QID18,TechEndorse_5,What attracts you to a technology or causes yo...,RO,Reputation for quality,5.0

Task 1. Counting the total number of respondents

In [14]:
count_of_responders = result['ResponseId'].nunique()
count_of_responders

49191

Task 2. Analysis of the completeness of respondents’ responses — check how many respondents answered all survey questions.

In [15]:
list_of_questions = schema['qname'].tolist()
list_of_questions

['TechEndorse_1',
 'TechEndorse_2',
 'TechEndorse_3',
 'TechEndorse_4',
 'TechEndorse_5',
 'TechEndorse_6',
 'TechEndorse_7',
 'TechEndorse_8',
 'TechEndorse_9',
 'TechEndorse_13',
 'TechEndorse_13_TEXT',
 'TechOppose_1',
 'TechOppose_2',
 'TechOppose_3',
 'TechOppose_5',
 'TechOppose_7',
 'TechOppose_9',
 'TechOppose_11',
 'TechOppose_13',
 'TechOppose_16',
 'TechOppose_15',
 'TechOppose_15_TEXT',
 'JobSatPoints_1',
 'JobSatPoints_2',
 'JobSatPoints_16',
 'JobSatPoints_3',
 'JobSatPoints_4',
 'JobSatPoints_5',
 'JobSatPoints_6',
 'JobSatPoints_7',
 'JobSatPoints_8',
 'JobSatPoints_9',
 'JobSatPoints_10',
 'JobSatPoints_11',
 'JobSatPoints_13',
 'JobSatPoints_14',
 'JobSatPoints_15',
 'JobSatPoints_15_TEXT',
 'SO_Actions_1',
 'SO_Actions_16',
 'SO_Actions_3',
 'SO_Actions_4',
 'SO_Actions_5',
 'SO_Actions_6',
 'SO_Actions_9',
 'SO_Actions_7',
 'SO_Actions_10',
 'SO_Actions_15',
 'SO_Actions_15_TEXT',
 'MainBranch',
 'Age',
 'EdLevel',
 'Employment',
 'EmploymentAddl',
 'WorkExp',
 'LearnCodeChoose',
 'LearnCode',
 'LearnCodeAI',
 'AILearnHow',
 'YearsCode',
 'DevType',
 'OrgSize',
 'ICorPM',
 'RemoteWork',
 'PurchaseInfluence',
 'TechEndorseIntro',
 'Industry',
 'JobSat',
 'AIThreat',
 'NewRole',
 'ToolCountWork',
 'ToolCountPersonal',
 'Country',
 'Currency',
 'CompTotal',
 'LanguageChoice',
 'Language',
 'LanguagesHaveEntry',
 'LanguagesWantEntry',
 'DatabaseChoice',
 'Database',
 'DatabaseHaveEntry',
 'DatabaseWantEntry',
 'PlatformChoice',
 'Platform',
 'PlatformHaveEntry',
 'PlatformWantEntry',
 'WebframeChoice',
 'Webframe',
 'WebframeHaveEntry',
 'WebframeWantEntry',
 'DevEnvsChoice',
 'DevEnvs',
 'DevEnvHaveEntry',
 'DevEnvWantEntry',
 'SOTags',
 'SOTagsHaveEntry',
 'SOTagsWant Entry',
 'OpSys',
 'OfficeStackAsync',
 'OfficeStackHaveEntry',
 'OfficeStackWantEntry',
 'CommPlatform',
 'CommPlatformHaveEntr',
 'CommPlatformWantEntr',
 'AIModelsChoice',
 'AIModels',
 'AIModelsHaveEntry',
 'AIModelsWantEntry',
 'SOAccount',
 'SOVisitFreq',
 'SODuration',
 'SOPartFreq',
 'SO_Dev_Content',
 'SOComm',
 'SOFriction',
 'AISelect',
 'AISent',
 'AIAcc',
 'AIComplex',
 'AITool',
 'AIFrustration',
 'AIExplain',
 'AIAgents',
 'AIAgentChange',
 'AIAgent_Uses',
 'AgentUsesGeneral',
 'AIAgentImpact',
 'AIAgentChallenges',
 'AIAgentKnowledge',
 'AIAgentKnowWrite',
 'AIAgentOrchestration',
 'AIAgentOrchWrite',
 'AIAgentObserveSecure',
 'AIAgentObsWrite',
 'AIAgentExternal',
 'AIAgentExtWrite',
 'AIHuman',
 'AIOpen']

In [16]:
common_columns = list(set(result.columns) & set(list_of_questions))
number_of_questions = len(common_columns)
number_of_questions

126

In [17]:
result['number_of_answered_questions'] = result[common_columns].notna().sum(axis=1)
result

,ResponseId,MainBranch,Age,EdLevel,Employment,EmploymentAddl,WorkExp,LearnCodeChoose,LearnCode,LearnCodeAI,...,AIAgentOrchWrite,AIAgentObserveSecure,AIAgentObsWrite,AIAgentExternal,AIAgentExtWrite,AIHuman,AIOpen,ConvertedCompYearly,JobSat,number_of_answered_questions
0,1,I am a developer by profession,25-34 years old,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",Employed,"Caring for dependents (children, elderly, etc.)",8.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools for...",...,NaN,NaN,NaN,ChatGPT,NaN,When I don’t trust AI’s answers,"Troubleshooting, profiling, debugging",61256.0,10.0,95
1,2,I am a developer by profession,25-34 years old,"Associate degree (A.A., A.S., etc.)",Employed,NaN,2.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools for...",...,NaN,NaN,NaN,NaN,NaN,When I don’t trust AI’s answers;When I want to...,All skills. AI is a flop.,104413.0,9.0,92
2,3,I am a developer by profession,35-44 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)","Independent contractor, freelancer, or self-em...",None of the above,10.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools for...",...,NaN,NaN,NaN,ChatGPT;Claude Code;GitHub Copilot;Google Gemini,NaN,When I don’t trust AI’s answers;When I want to...,"Understand how things actually work, problem s...",53061.0,8.0,95
3,4,I am a developer by profession,35-44 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Employed,None of the above,4.0,"Yes, I am not new to coding but am learning ne...","Other online resources (e.g. standard search, ...","Yes, I learned how to use AI-enabled tools for...",...,NaN,NaN,NaN,ChatGPT;Claude Code,NaN,When I don’t trust AI’s answers;When I want to...,NaN,36197.0,6.0,93
4,5,I am a developer by profession,35-44 years old,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)","Independent contractor, freelancer, or self-em...","Caring for dependents (children, elderly, etc.)",21.0,"No, I am not new to coding and did not learn n...",NaN,"Yes, I learned how to use AI-enabled tools for...",...,NaN,NaN,NaN,NaN,NaN,When I don’t trust AI’s answers,"critical thinking, the skill to define the tas...",60000.0,7.0,89
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49186,49187,I code primarily as a hobby,18-24 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Employed,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4
49187,49188,I am a developer by profession,45-54 years old,Some college/university study without earning ...,Employed,"Caring for dependents (children, elderly, etc.)",25.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools req...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9
49188,49189,I am a developer by profession,35-44 years old,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",Employed,None of the above,17.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools for...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9.0,69
49189,49190,I am a developer by profession,25-34 years old,"Professional degree (JD, MD, Ph.D, Ed.D, etc.)","Independent contractor, freelancer, or self-em...",None of the above,2.0,"Yes, I am not new to coding but am learning ne...",Videos (not associated with specific online co...,"Yes, I learned how to use AI-enabled tools for...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9
49190,49191,"I am not primarily a developer, but I write co...",18-24 years old,Some college/university study without earning ...,Student,Attending school (full-time),NaN,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools for...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,11

In [18]:
perfect_responders = result[result['number_of_answered_questions'] == number_of_questions]
print(len(perfect_responders))

0

Task 3. Fill empty values using the median or remove rows with empty values

In [19]:
fill_empty_values = result.copy()
delete_empty_values = result.copy()

In [20]:
median_value_for_fill = fill_empty_values['WorkExp'].median()
fill_empty_values['WorkExp'] = fill_empty_values['WorkExp'].fillna(median_value_for_fill).copy()
fill_empty_values['WorkExp'].info()

<class 'pandas.core.series.Series'>
RangeIndex: 49191 entries, 0 to 49190
Series name: WorkExp
Non-Null Count  Dtype
--------------  -----
49191 non-null  float64
dtypes: float64(1)
memory usage: 384.4 KB

In [21]:
result_mean = fill_empty_values['WorkExp'].mean().round(2)

result_median = fill_empty_values['WorkExp'].median()

result_mode = fill_empty_values['WorkExp'].mode()

print('Mean WorkExp:', result_mean)
print('Median WorkExp:', result_median)
print('Mode WorkExp:', result_mode)

Mean WorkExp: 12.94
Median WorkExp: 10.0
Mode WorkExp: 0    10.0
Name: WorkExp, dtype: float64

In [22]:
delete_empty_values.dropna(subset=['WorkExp'], inplace=True)
delete_empty_values['WorkExp'].info()

<class 'pandas.core.series.Series'>
Index: 42893 entries, 0 to 49189
Series name: WorkExp
Non-Null Count  Dtype
--------------  -----
42893 non-null  float64
dtypes: float64(1)
memory usage: 670.2 KB

In [23]:
result_mean = delete_empty_values['WorkExp'].mean().round(2)

result_median = delete_empty_values['WorkExp'].median()

result_mode = delete_empty_values['WorkExp'].mode()

print('Mean WorkExp:', result_mean)
print('Median WorkExp:', result_median)
print('Mode WorkExp:', result_mode)

Mean WorkExp: 13.37
Median WorkExp: 10.0
Mode WorkExp: 0    10.0
Name: WorkExp, dtype: float64

Task 4. Remote work analysis

In [24]:
count_remote_responders = result[result['RemoteWork'] == 'Remote']['RemoteWork'].count()
count_remote_responders

np.int64(10931)

Task 5. Determining the popularity of Python

In [26]:
python_responders_count = result['LanguageHaveWorkedWith'].str.contains('Python', na=False).sum()
python_responders_count

np.int64(18466)

In [28]:
percentage_of_python_responders = (python_responders_count/count_of_responders) * 100
print('% od Python users:',percentage_of_python_responders.round(2))

% od Python users: 37.54

Task 6. Analysis of ways to learn programming

In [29]:
count_online_studing_responders = result['LearnCode'].str.contains('Online Courses', case=False).sum()
count_online_studing_responders

10973

Task 7. Geographic analysis of Python developer compensation

In [31]:
result_country = result.copy()
result_country.dropna(subset=['Country'], inplace=True)

result_country['Country']

0                         Ukraine
1                     Netherlands
2                         Ukraine
3                         Ukraine
4                         Ukraine
                   ...
49177    United States of America
49178                     Germany
49179                      Brazil
49180                      Canada
49188                       Italy
Name: Country, Length: 35437, dtype: object

In [32]:
result_country.dropna(subset=['LanguageHaveWorkedWith'], inplace=True)
result_country['LanguageHaveWorkedWith']

0                         Bash/Shell (all shells);Dart;SQL
1                                                     Java
2                      Dart;HTML/CSS;JavaScript;TypeScript
3                                          Java;Kotlin;SQL
4        C;C#;C++;Delphi;HTML/CSS;Java;JavaScript;Lua;P...
                               ...
49176    Bash/Shell (all shells);HTML/CSS;JavaScript;Py...
49177    Bash/Shell (all shells);HTML/CSS;Lisp;PowerShe...
49178                   Bash/Shell (all shells);C;C++;Rust
49179                        Bash/Shell (all shells);Swift
49180                  Assembly;C#;Go;Java;JavaScript;Rust
Name: LanguageHaveWorkedWith, Length: 31671, dtype: object

In [33]:
python_responders_with_country = result_country['LanguageHaveWorkedWith'].str.contains('Python', case=False, na=False)
result_country['LanguageHaveWorkedWithPython'] = python_responders_with_country
result_country['LanguageHaveWorkedWithPython']

0        False
1        False
2        False
3        False
4         True
         ...
49176     True
49177     True
49178    False
49179    False
49180    False
Name: LanguageHaveWorkedWithPython, Length: 31671, dtype: bool

In [34]:
result_country = result_country[result_country['LanguageHaveWorkedWithPython'] == True]
result_country

,ResponseId,MainBranch,Age,EdLevel,Employment,EmploymentAddl,WorkExp,LearnCodeChoose,LearnCode,LearnCodeAI,...,AIAgentObserveSecure,AIAgentObsWrite,AIAgentExternal,AIAgentExtWrite,AIHuman,AIOpen,ConvertedCompYearly,JobSat,number_of_answered_questions,LanguageHaveWorkedWithPython
4,5,I am a developer by profession,35-44 years old,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)","Independent contractor, freelancer, or self-em...","Caring for dependents (children, elderly, etc.)",21.0,"No, I am not new to coding and did not learn n...",NaN,"Yes, I learned how to use AI-enabled tools for...",...,NaN,NaN,NaN,NaN,When I don’t trust AI’s answers,"critical thinking, the skill to define the tas...",60000.0,7.0,89,True
7,8,I am a developer by profession,35-44 years old,"Professional degree (JD, MD, Ph.D, Ed.D, etc.)",Employed,Engaged in paid work (20-29 hours per week);Tr...,22.0,"Yes, I am not new to coding but am learning ne...",Books / Physical media;Technical documentation...,"Yes, I learned how to use AI-enabled tools for...",...,NaN,NaN,NaN,NaN,When I want to learn best practices;When I wan...,"Innovation, system design",72000.0,6.0,93,True
8,9,I am a developer by profession,25-34 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Employed,"Caring for dependents (children, elderly, etc....",9.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools for...",...,NaN,NaN,NaN,NaN,NaN,NaN,70000.0,8.0,73,True
15,16,I am a developer by profession,18-24 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Student,Engaged in paid work (20-29 hours per week);En...,5.0,"Yes, I am new to coding or currently a student",Online Courses or Certification (includes all ...,"No, I learned something that was not related t...",...,Galileo;Honeycomb;Metero;New Relic;opik;Snyk,NaN,ChatGPT;AgentGPT;Auto-GPT;Devin AI;Glean (Ente...,NaN,When I don’t trust AI’s answers;When I have et...,5,NaN,7.0,99,True
17,18,I am a developer by profession,25-34 years old,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",Employed,NaN,1.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools for...",...,NaN,NaN,NaN,NaN,When I want to learn best practices;When I hav...,NaN,NaN,6.0,89,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49143,49144,I am a developer by profession,25-34 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Not employed,None of the above,4.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools req...",...,NaN,NaN,NaN,NaN,When I don’t trust AI’s answers;When I want to...,Advocating for oneself and community building....,NaN,2.0,92,True
49145,49146,I am a developer by profession,35-44 years old,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)","Independent contractor, freelancer, or self-em...","Caring for dependents (children, elderly, etc....",18.0,"Yes, I am not new to coding but am learning ne...","Other online resources (e.g. standard search, ...","Yes, I learned how to use AI-enabled tools req...",...,NaN,NaN,ChatGPT;GitHub Copilot;Google Gemini,NaN,When I don’t trust AI’s answers;When I want to...,Connecting technical problems to business need...,NaN,10.0,96,True
49175,49176,I am a developer by profession,25-34 years old,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",Employed,NaN,4.0,"Yes, I am not new to coding but am learning ne...","Other online resources (e.g. standard search, ...","Yes, I learned how to use AI-enabled tools for...",...,Grafana + Prometheus,NaN,ChatGPT;Claude Code;Google Gemini,Cursor,When I don’t trust AI’s answers;When I want to...,Software Architecture,NaN,8.0,105,True
49176,49177,I am a developer by profession,25-34 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Employed,Attending school (part-time),5.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools req...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9.0,91,True
49177,49178,I am learning to code,35-44 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Not employed,Engaged in paid work (less than 10 hours per w...,9.0,"Yes, I am not new to coding but am learning ne...","Other online resources (e.g. standard search, ...","Yes, I learned how to use AI-enabled tools for...",...,NaN,NaN,NaN,NaN,When I want to fully understand something;When...,"Exposition on the ""how"" or ""why"" instead of th...",NaN,NaN,82,True

In [35]:
#fill empty values with median

result_country['ConvertedCompYearly'].info()

<class 'pandas.core.series.Series'>
Index: 18466 entries, 4 to 49177
Series name: ConvertedCompYearly
Non-Null Count  Dtype
--------------  -----
12765 non-null  float64
dtypes: float64(1)
memory usage: 288.5 KB

In [36]:
fill_empty_values_median = result_country.copy()

result_country_median = fill_empty_values_median['ConvertedCompYearly'].median()
fill_empty_values_median['ConvertedCompYearly'] = fill_empty_values_median['ConvertedCompYearly'].fillna(result_country_median)
fill_empty_values_median['ConvertedCompYearly'].info()

<class 'pandas.core.series.Series'>
Index: 18466 entries, 4 to 49177
Series name: ConvertedCompYearly
Non-Null Count  Dtype
--------------  -----
18466 non-null  float64
dtypes: float64(1)
memory usage: 288.5 KB

In [37]:
fill_mean = fill_empty_values_median.groupby('Country', as_index=False).agg(
    MeanCompensationByCountry=('ConvertedCompYearly', 'mean'),
    MedianCompensationByCountry=('ConvertedCompYearly', 'median')
).round(2)
fill_mean

,Country,MeanCompensationByCountry,MedianCompensationByCountry
0,Afghanistan,35946.50,33000.0
1,Albania,62008.80,76800.0
2,Algeria,59570.04,76800.0
3,Andorra,226103.50,226103.5
4,Angola,76800.00,76800.0
...,...,...,...
162,"Venezuela, Bolivarian Republic of...",27358.57,12000.0
163,Viet Nam,131429.68,76800.0
164,Yemen,47553.00,56920.5
165,Zambia,36013.86,14960.0
166,Zimbabwe,52342.86,70000.0

In [38]:
#without empty values - delete

delete_empty_values_compansation = result_country.copy()

delete_empty_values_compansation.dropna(subset=['ConvertedCompYearly'], inplace=True)
delete_empty_values_compansation['ConvertedCompYearly'].info()

<class 'pandas.core.series.Series'>
Index: 12765 entries, 4 to 49106
Series name: ConvertedCompYearly
Non-Null Count  Dtype
--------------  -----
12765 non-null  float64
dtypes: float64(1)
memory usage: 199.5 KB

In [39]:
delete_empty = delete_empty_values_compansation.groupby('Country', as_index=False).agg(
    MeanCompensationByCountry=('ConvertedCompYearly', 'mean'),
    MedianCompensationByCountry=('ConvertedCompYearly', 'median')
).round(2)
delete_empty

,Country,MeanCompensationByCountry,MedianCompensationByCountry
0,Afghanistan,22328.67,1000.0
1,Albania,47217.60,50000.0
2,Algeria,20187.29,7088.0
3,Andorra,226103.50,226103.5
4,Antigua and Barbuda,1.00,1.0
...,...,...,...
148,"Venezuela, Bolivarian Republic of...",9908.65,3000.0
149,Viet Nam,218837.17,8254.0
150,Yemen,32929.50,23672.0
151,Zambia,5424.25,3206.0
152,Zimbabwe,34000.00,25500.0

Task 8. Analysis of the education of the highest paid specialists

In [40]:
sorted_result = result.sort_values('ConvertedCompYearly', ascending=False)
sorted_result[['ResponseId', 'EdLevel', 'ConvertedCompYearly']].head(5)

,ResponseId,EdLevel,ConvertedCompYearly
34267,34268,"Associate degree (A.A., A.S., etc.)",50000000.0
28700,28701,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",33552715.0
43143,43144,"Associate degree (A.A., A.S., etc.)",18387548.0
35353,35354,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",15430267.0
45971,45972,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",13921760.0

Task 9. Analysis of Python popularity by age category

In [41]:
result.dropna(subset=['LanguageHaveWorkedWith'], inplace=True)

new_python_responders= result['LanguageHaveWorkedWith'].str.contains('Python', case=False, na=False)
result['LanguageHaveWorkedWithPython'] = new_python_responders
result = result[result['LanguageHaveWorkedWithPython'] == True]

result['Age'].info()

unique_age_category = result['Age'].nunique()
unique_age_category

popul_python_age = result.groupby('Age', as_index=False).agg(
    TopPythonAge=('LanguageHaveWorkedWithPython', 'sum')
)

popul_python_age['PercOfAge'] = (((popul_python_age['TopPythonAge'])/(new_python_responders.sum()))*100).round(2)
popul_python_age.sort_values('PercOfAge', ascending=False)

<class 'pandas.core.series.Series'>
Index: 18466 entries, 4 to 49177
Series name: Age
Non-Null Count  Dtype
--------------  -----
18466 non-null  object
dtypes: object(1)
memory usage: 288.5+ KB

                 Age  TopPythonAge  PercOfAge
1    25-34 years old          6102      33.04
2    35-44 years old          4862      26.33
0    18-24 years old          3684      19.95
3    45-54 years old          2424      13.13
4    55-64 years old           978       5.30
5  65 years or older           298       1.61
6  Prefer not to say           118       0.64

Task 10. Analysis of industries among high-paid remote workers

In [42]:
remote_result = result.copy()
remote_responders = remote_result[remote_result['RemoteWork'] == 'Remote']['RemoteWork']
remote_result['Remote'] = remote_responders
remote_result.dropna(subset=['Remote'], inplace=True)

percentile_75 = remote_result['ConvertedCompYearly'].quantile(0.75)
remote_responders_percentile_75 = remote_result[remote_result['ConvertedCompYearly'] > percentile_75]
popular_industries = remote_responders_percentile_75['Industry'].value_counts()

popular_industries

Industry
Software Development                          430
Fintech                                        76
Healthcare                                     61
Other:                                         60
Internet, Telecomm or Information Services     54
Media & Advertising Services                   28
Banking/Financial Services                     25
Computer Systems Design and Services           25
Government                                     24
Transportation, or Supply Chain                23
Retail and Consumer Services                   19
Energy                                         18
Insurance                                      16
Manufacturing                                  10
Higher Education                                7
Name: count, dtype: int64